#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

# reminder compile book: 
# conda activate pygisbookgw
# cd Documents/github/pyGIS/
# jupyter-book build pygis
# ghp-import -n -p  -c 'pygis.io' -f pygis/_build/html


#######################################################################################
# Book settings
title                       : Python Open Source Spatial Programming & Remote Sensing  # The title of the book. Will be placed in the left navbar.
author                      : Michael Mann, Steven Chao, Jordan Graesser, Nina Feldman  # The author of the book
logo                        : pygis.png  # A path to the book logo
sphinx:
  config:
    html_show_copyright: false
    html_baseurl: 'https://pygis.io/' #    must have / after last character 'https://mmann1123.github.io/pyGIS/'
    bibtex_reference_style: author_year
    bibtex_bibfiles: reference.bib
    language: en

    # templates_path:
      # - _templates
  extra_extensions:
    - sphinx_sitemap
    - sphinxcontrib.bibtex
    - sphinx_inline_tabs
    #  myst_enable_extensions = ["dollarmath", "amsmath"]

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : force  #auto, cache, off ,force
  exclude_patterns          : 
                              [ 
                              #   'a_*',
                              # 'b_*',
                              # 'c_*',
                              # 'd_*', 
                              #  'e_*',
                              # 'f_*',
                              ]     # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

  #'e_attributes*','e_extraction*','e_new_vectors*','e_raster_op_intro*','e_raster_reproject*',
  timeout: 100

only_build_toc_files: true

 
# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

repository:
  url                       : https://github.com/mmann1123/pyGIS  # The URL to your book's repository
  path_to_book              : "./pygis"  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

html:
  use_edit_page_button:         true
  use_issues_button:            true
  home_page_in_navbar:          true
  use_repository_button:        true
  google_analytics_id       :  'G-MQPNBR6XWJ' #  'UA-192844775-1' # A GA id that can be used to track book views.
  extra_footer              :  
  extra_footer: |
        <div>
            <b>Supported by:</b>  <br>
            <a href="https://geography.columbian.gwu.edu/">
         <img alt="GW Geography" src="../_static/global/GWBlue.png"
          width="300" align="left">
        </div>
        <div>
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/" ><img align="right" alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a> 
        </div><br><br>
        <div>
        <a rel="Reference" href="https://zenodo.org/badge/latestdoi/344683467" ><img align="right" alt="Reference our work" style="border-width:0" src="https://zenodo.org/badge/344683467.svg" /></a> 
        </div>
    
  # Will be displayed underneath the footer. width=150" height="70"
 
  baseurl: "https://pygis.io/"   # for sitemap  https://sphinx-sitemap.readthedocs.io/en/latest/search-optimization.html

 

#######################################################################################
# Launch button settings

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname:                 book.tex

 # inserted into _templates/_layout.html  
# <!-- Google tag (gtag.js) -->
# <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZDC6C7GLDY"></script>
# <script>
#   window.dataLayer = window.dataLayer || [];
#   function gtag(){dataLayer.push(arguments);}
#   gtag('js', new Date());

#   gtag('config', 'G-ZDC6C7GLDY');
# </script>
